#!/bin/bash

set -e

MULTIMC_FOLDER=$1
TMP=/tmp/extract-icons
VERSION=1.7.10
INSTANCE=lökcraft1.3

mkdir -p $TMP
cp $MULTIMC_FOLDER/versions/$VERSION/$VERSION.jar $TMP/$VERSION.jar
mkdir -p $TMP/minecraft
cd $TMP/minecraft
unzip -n $TMP/$VERSION.jar

IFS=$'\n'
find "$MULTIMC_FOLDER/instances/$INSTANCE/minecraft/mods" -iname "*.jar" | while read MOD_PATH
do
    JAR_NAME=`basename $MOD_PATH`
    MOD_NAME=${JAR_NAME%????}
    echo "processing $JAR_NAME ($MOD_NAME)"

    cp $MOD_PATH $TMP/$JAR_NAME
    mkdir -p $TMP/$MOD_NAME
    echo "cd $TMP/$MOD_NAME"
    cd $TMP/$MOD_NAME
    unzip -n $TMP/$JAR_NAME
done
IFS=' '
